name: 'generate_port'
description: 'generate_port'
outputs:
  random-port:
    description: "Random port"
    value: ${{ steps.random-port-generator.outputs.random-port }}
runs:
  using: "composite"
  steps:
  - id: random-port-generator
    run: echo "random-port=$(bash $GITHUB_WORKSPACE/.github/actions/generate-random-port/generate_port.sh)" >> $GITHUB_OUTPUT
    shell: bash